### Get all posts
GET http://localhost:8080/api/posts

### Get all tags
GET http://localhost:8080/api/tags

### Find posts by query
GET http://localhost:8080/api/posts?query=lorem

### Find posts by tag
GET http://localhost:8080/api/posts?tag=hello-world

### Find posts by both
GET http://localhost:8080/api/posts?tag=lorem-ipsum&query=lorem

### Get one post
GET http://localhost:8080/api/posts/1

### Get all comments in post
GET http://localhost:8080/api/posts/1/comments

### Get all tags in post
GET http://localhost:8080/api/posts/1/tags

### Get one comment
GET http://localhost:8080/api/posts/1/comments/1

# These require authentication with JWT
# Just run the /api/login POST request, copy the Authorization header from the response
# and paste it to the other requests.

### Delete post without authorization (error)
DELETE http://localhost:8080/api/posts/1

### Login
POST http://localhost:8080/api/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin

### Delete post with authorization
DELETE http://localhost:8080/api/posts/3
Authorization: Bearer tokenhere

### Delete comment
DELETE http://localhost:8080/api/posts/1/comments/1
Authorization: Bearer tokenhere
