### Get all posts
GET http://localhost:8080/api/posts

### Find posts by query
GET http://localhost:8080/api/posts?query=world hello

### Get one post
GET http://localhost:8080/api/posts/1

### Delete post
DELETE http://localhost:8080/api/posts/1

### Get all comments in post
GET http://localhost:8080/api/posts/1/comments

### Get one comment
GET http://localhost:8080/api/posts/1/comments/1

### Delete comment
DELETE http://localhost:8080/api/posts/1/comments/1
